/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPrescriptionsRouteImport } from './routes/_app/prescriptions'
import { Route as AppPatientsRouteImport } from './routes/_app/patients'
import { Route as AppDoctorsRouteImport } from './routes/_app/doctors'
import { Route as AppDepartmentsRouteImport } from './routes/_app/departments'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAssistantRouteImport } from './routes/_app/assistant'
import { Route as AppAppointmentsRouteImport } from './routes/_app/appointments'
import { Route as AppPrescriptionsIdRouteImport } from './routes/_app/prescriptions.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsIdRoute = AppPrescriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPrescriptionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/appointments': typeof AppAppointmentsRoute
  '/assistant': typeof AppAssistantRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/doctors': typeof AppDoctorsRoute
  '/patients': typeof AppPatientsRoute
  '/prescriptions': typeof AppPrescriptionsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/prescriptions/$id': typeof AppPrescriptionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/appointments': typeof AppAppointmentsRoute
  '/assistant': typeof AppAssistantRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/doctors': typeof AppDoctorsRoute
  '/patients': typeof AppPatientsRoute
  '/prescriptions': typeof AppPrescriptionsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/prescriptions/$id': typeof AppPrescriptionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/doctors': typeof AppDoctorsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/prescriptions': typeof AppPrescriptionsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/prescriptions/$id': typeof AppPrescriptionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/appointments'
    | '/assistant'
    | '/dashboard'
    | '/departments'
    | '/doctors'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/prescriptions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/appointments'
    | '/assistant'
    | '/dashboard'
    | '/departments'
    | '/doctors'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/prescriptions/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/appointments'
    | '/_app/assistant'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/doctors'
    | '/_app/patients'
    | '/_app/prescriptions'
    | '/_app/reports'
    | '/_app/prescriptions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prescriptions': {
      id: '/_app/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctors': {
      id: '/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prescriptions/$id': {
      id: '/_app/prescriptions/$id'
      path: '/$id'
      fullPath: '/prescriptions/$id'
      preLoaderRoute: typeof AppPrescriptionsIdRouteImport
      parentRoute: typeof AppPrescriptionsRoute
    }
  }
}

interface AppPrescriptionsRouteChildren {
  AppPrescriptionsIdRoute: typeof AppPrescriptionsIdRoute
}

const AppPrescriptionsRouteChildren: AppPrescriptionsRouteChildren = {
  AppPrescriptionsIdRoute: AppPrescriptionsIdRoute,
}

const AppPrescriptionsRouteWithChildren =
  AppPrescriptionsRoute._addFileChildren(AppPrescriptionsRouteChildren)

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPrescriptionsRoute: typeof AppPrescriptionsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPrescriptionsRoute: AppPrescriptionsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
